import type { ParityRow } from './manifest-types.ts';

export const parityManifest: readonly ParityRow[] = [
  {
    id: 'workbook',
    unit: { assertions: ['workbook.canonical-roundtrip', 'workbook.empty-input'] },
    component: { assertions: ['workbook.sheet-lifecycle'] },
    browser: { assertions: ['workbook.import-export'] },
    visual: { assertions: ['workbook.initial-grid'] },
  },
  {
    id: 'selection',
    unit: { assertions: ['selection.normalize-range'] },
    component: { assertions: ['selection.keyboard-extension'] },
    browser: { assertions: ['selection.pointer-drag'] },
    visual: { assertions: ['selection.active-range'] },
  },
  {
    id: 'editing',
    unit: { assertions: ['editing.commit-cancel'] },
    component: { assertions: ['editing.inline-editor'] },
    browser: { assertions: ['editing.ime-input'] },
    visual: { assertions: ['editing.editor-overlay'] },
  },
  {
    id: 'history',
    unit: { assertions: ['history.undo-redo'] },
    component: { assertions: ['history.command-controls'] },
    browser: { assertions: ['history.shortcuts'] },
    visual: { notApplicable: 'History state has no distinct visual output beyond the restored workbook.' },
  },
  {
    id: 'formatting',
    unit: { assertions: ['formatting.commands'] },
    component: { assertions: ['formatting.toolbar'] },
    browser: { assertions: ['formatting.shortcuts'] },
    visual: { assertions: ['formatting.styled-cells'] },
  },
  {
    id: 'structure',
    unit: { assertions: ['structure.row-column-operations'] },
    component: { assertions: ['structure.sheet-tabs'] },
    browser: { assertions: ['structure.resize-drag'] },
    visual: { assertions: ['structure.hidden-resized-grid'] },
  },
  {
    id: 'ranges',
    unit: { assertions: ['ranges.merge-autofill'] },
    component: { assertions: ['ranges.name-box'] },
    browser: { assertions: ['ranges.drag-fill'] },
    visual: { assertions: ['ranges.merged-selection'] },
  },
  {
    id: 'view',
    unit: { assertions: ['view.frozen-geometry'] },
    component: { assertions: ['view.scroll-sync'] },
    browser: { assertions: ['view.zoom-scroll'] },
    visual: { assertions: ['view.frozen-panes'] },
  },
  {
    id: 'clipboard',
    unit: { assertions: ['clipboard.transform'] },
    component: { assertions: ['clipboard.menu-actions'] },
    browser: { assertions: ['clipboard.system-bridge'] },
    visual: { notApplicable: 'Plain clipboard transfer has no persistent visual state.' },
  },
  {
    id: 'data-tools',
    unit: { assertions: ['tools.sort-total-order', 'tools.validation-all-sheets'] },
    component: { assertions: ['tools.filter-controls'] },
    browser: { assertions: ['tools.filter-menu'] },
    visual: { assertions: ['tools.filtered-grid'] },
  },
  {
    id: 'formulas',
    unit: { assertions: ['formulas.references', 'formulas.computation'] },
    component: { assertions: ['formulas.editor-display'] },
    browser: { assertions: ['formulas.keyboard-commit'] },
    visual: { notApplicable: 'Formula computation is evidenced by rendered values in non-visual lanes.' },
  },
  {
    id: 'output',
    unit: { assertions: ['output.print-layout'] },
    component: { assertions: ['output.print-dialog'] },
    browser: { assertions: ['output.export-download'] },
    visual: { assertions: ['output.print-preview'] },
  },
  {
    id: 'input',
    unit: { assertions: ['input.keymap'] },
    component: { assertions: ['input.desktop-editing'] },
    browser: { assertions: ['input.touch-gestures'] },
    visual: { assertions: ['input.touch-handles'] },
  },
  {
    id: 'localization',
    unit: { assertions: ['locale.message-resolution'] },
    component: { assertions: ['locale.switch-language'] },
    browser: { assertions: ['locale.browser-default'] },
    visual: { assertions: ['locale.localized-ui'] },
  },
  {
    id: 'correction.empty-workbook',
    unit: { assertions: ['correction.empty-workbook'] },
    component: { notApplicable: 'The correction is enforced while constructing the workbook model.' },
    browser: { notApplicable: 'The corrected behavior does not depend on browser APIs.' },
    visual: { notApplicable: 'The empty-workbook invariant is structural rather than pixel-specific.' },
  },
  {
    id: 'correction.validation-all-sheets',
    unit: { assertions: ['correction.validation-all-sheets'] },
    component: { notApplicable: 'Workbook-wide validation is a pure selector contract.' },
    browser: { notApplicable: 'The corrected validation scope does not depend on browser APIs.' },
    visual: { notApplicable: 'Issue ordering and sheet coverage are data-level evidence.' },
  },
  {
    id: 'correction.sort-rendered-values',
    unit: { assertions: ['correction.sort-rendered-values'] },
    component: { notApplicable: 'Rendered-value ordering is a pure data transformation.' },
    browser: { notApplicable: 'The corrected sort order does not depend on browser APIs.' },
    visual: { notApplicable: 'The total order is asserted directly rather than by pixels.' },
  },
  {
    id: 'correction.resource-cleanup',
    unit: { notApplicable: 'Browser resource ownership requires real event and timer APIs.' },
    component: { notApplicable: 'Unmount rendering alone cannot prove global resource release.' },
    browser: { assertions: ['correction.resource-cleanup'] },
    visual: { notApplicable: 'Resource cleanup has no visible state after disposal.' },
  },
  {
    id: 'correction.printable-cells',
    unit: { assertions: ['correction.printable-cells'] },
    component: { notApplicable: 'Printable-cell inclusion is decided by the print layout engine.' },
    browser: { notApplicable: 'The corrected layout is deterministic without browser APIs.' },
    visual: { assertions: ['correction.printable-cells-visual'] },
  },
];
