import {
  createFontMetrics,
  migrateLegacyWorkbook,
  type RenderEnvironment,
  type SpreadsheetDocument,
  type SpreadsheetTemplate,
} from 'tego-sheet';

export interface InvoiceOutputFixture {
  readonly document: SpreadsheetDocument;
  readonly template: SpreadsheetTemplate;
  readonly data: Readonly<{
    customer: Readonly<{ name: string; address: string }>;
    invoice: Readonly<{ id: string; currency: string }>;
    items: readonly Readonly<{
      description: string;
      quantity: number;
      amount: number;
    }>[];
  }>;
  readonly environment: RenderEnvironment;
}

export function createInvoiceOutputFixture(): InvoiceOutputFixture {
  const migrated = migrateLegacyWorkbook(
    [
      {
        name: 'Invoice',
        rows: {
          len: 30,
          0: { cells: { 0: { text: 'INVOICE' }, 4: { text: 'Invoice number' } } },
          2: { cells: { 0: { text: 'Customer' }, 4: { text: 'Number' } } },
          4: {
            cells: {
              0: { text: 'Description' },
              3: { text: 'Quantity' },
              4: { text: 'Unit price' },
              5: { text: 'Amount' },
            },
          },
          6: { cells: { 0: { text: 'Hosting' }, 3: { text: '1' }, 5: { text: '29' } } },
          7: { cells: { 0: { text: 'Support' }, 3: { text: '4' }, 5: { text: '75' } } },
          8: { cells: { 0: { text: 'Training' }, 3: { text: '2' }, 5: { text: '240' } } },
          14: { cells: { 0: { text: 'Terms and payment details' } } },
          18: { cells: { 0: { text: 'Thank you for your business.' } } },
        },
        cols: { len: 6 },
      },
    ],
    {
      ids: {
        documentId: () => 'invoice-document',
        sheetId: () => 'invoice-sheet',
      },
    },
  );
  if (!migrated.ok) {
    throw new TypeError(migrated.diagnostics.map(({ message }) => message).join('\n'));
  }

  const template: SpreadsheetTemplate = {
    id: 'invoice-template' as never,
    name: 'Customer invoice',
    bindings: [
      {
        id: 'customer-name' as never,
        type: 'value',
        target: { sheetId: 'invoice-sheet' as never, row: 2, column: 0 },
        expression: 'customer.name',
      },
      {
        id: 'invoice-number' as never,
        type: 'value',
        target: { sheetId: 'invoice-sheet' as never, row: 2, column: 4 },
        expression: 'invoice.id',
      },
    ],
    printProfiles: [
      {
        id: 'invoice-a4',
        name: 'Invoice · A4',
        targets: [{ type: 'sheet', sheetId: 'invoice-sheet' as never }],
        page: {
          paper: { type: 'A4' },
          orientation: 'portrait',
          margins: { top: 18, right: 16, bottom: 18, left: 16 },
          scale: { type: 'fixed', value: 1 },
        },
        repeatRows: {
          sheetId: 'invoice-sheet' as never,
          start: { row: 0, column: 0 },
          end: { row: 4, column: 5 },
        },
        manualBreaks: [{ sheetId: 'invoice-sheet' as never, beforeRow: 14 }],
        header: { right: 'Invoice {{page}}' },
        footer: { center: 'Generated by tego-sheet · {{page}}/{{pages}}' },
        showGridlines: false,
        showHeadings: false,
      },
    ],
  };

  const data = Object.freeze({
    customer: Object.freeze({ name: 'Acme GmbH', address: 'Berlin' }),
    invoice: Object.freeze({ id: 'INV-2026-042', currency: 'EUR' }),
    items: Object.freeze([
      Object.freeze({ description: 'Hosting', quantity: 1, amount: 29 }),
      Object.freeze({ description: 'Support', quantity: 4, amount: 75 }),
      Object.freeze({ description: 'Training', quantity: 2, amount: 240 }),
    ]),
  });

  const environment: RenderEnvironment = {
    locale: 'en-US',
    timeZone: 'UTC',
    dateSystem: 'excel-1900',
    clock: new Date('2026-07-25T00:00:00.000Z'),
    fontMetrics: createFontMetrics({
      fonts: { Arial: { averageAdvance: 6, lineHeight: 12 } },
      fallbackFont: 'Arial',
      fallback: { averageAdvance: 6, lineHeight: 12 },
    }),
  };

  return Object.freeze({
    document: migrated.document,
    template: Object.freeze(template),
    data,
    environment: Object.freeze(environment),
  });
}
