import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarItemConfig } from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';

function sidebarError(path: string, expected: string): never {
  throw new TypeError(`Generated TypeDoc sidebar ${path} ${expected}.`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function assertString(value: unknown, path: string): void {
  if (typeof value !== 'string' || value.length === 0)
    sidebarError(path, 'must be a non-empty string');
}

function assertSidebarConfig(value: unknown, path: string): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) => assertSidebarItem(item, `${path}[${index}]`));
    return;
  }
  if (!isRecord(value)) sidebarError(path, 'must be an array or category shorthand object');
  for (const [label, items] of Object.entries(value)) {
    assertString(label, `${path} category label`);
    assertSidebarConfig(items, `${path}.${label}`);
  }
}

function assertSidebarItem(value: unknown, path: string): void {
  if (typeof value === 'string') {
    assertString(value, path);
    return;
  }
  if (!isRecord(value)) sidebarError(path, 'must be a string or sidebar item object');
  if (value.type === undefined) {
    assertSidebarConfig(value, path);
    return;
  }
  assertString(value.type, `${path}.type`);
  switch (value.type) {
    case 'doc':
    case 'ref':
      assertString(value.id, `${path}.id`);
      return;
    case 'category':
      assertString(value.label, `${path}.label`);
      assertSidebarConfig(value.items, `${path}.items`);
      return;
    case 'autogenerated':
      assertString(value.dirName, `${path}.dirName`);
      return;
    case 'html':
      assertString(value.value, `${path}.value`);
      return;
    case 'link':
      assertString(value.label, `${path}.label`);
      assertString(value.href, `${path}.href`);
      return;
    default:
      sidebarError(`${path}.type`, `has unsupported value ${JSON.stringify(value.type)}`);
  }
}

function assertGeneratedSidebar(value: unknown): asserts value is SidebarItemConfig[] {
  if (!Array.isArray(value)) sidebarError('export', 'must be an array');
  value.forEach((item, index) => assertSidebarItem(item, `export[${index}]`));
}

export function parseGeneratedSidebar(value: unknown): SidebarItemConfig[] {
  assertGeneratedSidebar(value);
  return value;
}

export function createDocumentationSidebars(typedocSidebar: SidebarItemConfig[]): SidebarsConfig {
  return {
    docsSidebar: [
      {
        type: 'category',
        label: 'Getting Started',
        items: [
          'getting-started/installation',
          'getting-started/quick-start',
          'getting-started/styling-and-sizing',
        ],
      },
      {
        type: 'category',
        label: 'Core Concepts',
        items: [
          'concepts/controlled-and-uncontrolled',
          'concepts/workbook-data',
          'concepts/refs-and-commands',
          'concepts/callbacks-and-errors',
        ],
      },
      {
        type: 'category',
        label: 'Guides',
        items: [
          'guides/custom-chrome',
          'guides/locales',
          'guides/validation-and-filtering',
          'guides/frozen-panes-and-layout',
          'guides/printing',
        ],
      },
      {
        type: 'category',
        label: 'Migration',
        items: ['migration/from-x-data-spreadsheet'],
      },
      {
        type: 'category',
        label: 'API Reference',
        link: { type: 'doc', id: 'api/index' },
        items: typedocSidebar,
      },
    ],
  };
}
