/**
 * React component, imperative handle, and serializable public contracts for `tego-sheet`.
 *
 * @packageDocumentation
 */
import './ui/styles/index.less';

export type {
  ActiveSheetChangeEvent,
  AutoFilterData,
  AutoFilterItemData,
  AutoFilterSortData,
  BorderLine,
  BorderMode,
  CellAddress,
  CellBorders,
  CellData,
  CellEditEvent,
  CellPoint,
  CellRange,
  CellsData,
  CellStyle,
  ChangeSource,
  ColsData,
  ColumnData,
  FilterDefinition,
  FontStyle,
  HorizontalAlign,
  JsonValue,
  LocaleDefinition,
  LocaleMessages,
  PasteEvent,
  RowData,
  RowsData,
  Selection,
  SheetColumnOptions,
  SheetData,
  SheetId,
  SheetOptions,
  SheetRowOptions,
  SheetTabItem,
  SheetTabsRenderProps,
  TegoSheetError,
  TegoSheetErrorCode,
  ToolbarAction,
  ToolbarRenderProps,
  ValidationData,
  ValidationIssue,
  ValidationOperator,
  ValidationResult,
  ValidationRule,
  ValidationType,
  VerticalAlign,
  WorkbookChange,
  WorkbookChangeKind,
} from './core';
export { TegoSheetException } from './core';
export {
  createSpreadsheetDocument,
  migrateLegacyWorkbook,
  parseSpreadsheetDocument,
  serializeSpreadsheetDocument,
} from './document';
export type {
  BindingId,
  Cell,
  CellInput,
  CreateDocumentOptions,
  Diagnostic,
  DiagnosticDomain,
  DiagnosticLocation,
  DiagnosticStage,
  DocumentCellAddress,
  DocumentCellRange,
  DocumentDiagnostic,
  DocumentDiagnosticCode,
  DocumentId,
  DocumentLimits,
  DocumentParseOptions,
  DocumentParseResult,
  DocumentSheetId,
  ExtensionStore,
  LegacyMigrationDiagnosticCode,
  LegacyMigrationIdFactory,
  LegacyMigrationOptions,
  MigrationDiagnostic,
  MigrationResult,
  ObjectId,
  PrintMargins,
  PrintProfile,
  RegistryEntry,
  ResourceId,
  ResourceMetadata,
  ResourceStore,
  Sheet,
  SheetColumn,
  SheetFilter,
  SheetFilterItem,
  SheetRange,
  SheetRow,
  SparseCell,
  SpreadsheetDocument,
  SpreadsheetTemplate,
  StyleId,
  StyleRegistry,
  TemplateId,
  ValidationId,
  ValidationRegistry,
  Workbook,
  WorkbookSettings,
} from './document';
/** A zero-based Workbook 2.0 cell coordinate. */
export type { CellPoint as DocumentCellPoint } from './document';
export { TegoSheet } from './react/tego-sheet';
export type {
  SheetTabsRenderer,
  TegoSheetHandle,
  TegoSheetProps,
  ToolbarRenderer,
} from './react/tego-sheet.types';
