/**
 * React component, imperative handle, and serializable public contracts for `tego-sheet`.
 *
 * @packageDocumentation
 */
import './ui/styles/index.less';

export type {
  ActiveSheetChangeEvent,
  AddSheetCommand,
  AutofillCommand,
  AutoFilterData,
  AutoFilterItemData,
  AutoFilterSortData,
  BorderLine,
  BorderMode,
  CellAddress,
  CellBorders,
  CellData,
  CellEditEvent,
  CellPoint,
  CellRange,
  CellsData,
  CellStyle,
  ChangeSource,
  ClearContentsCommand,
  ClearFilterCommand,
  ClearFormatCommand,
  ColsData,
  ColumnData,
  DeleteSheetCommand,
  FilterDefinition,
  FontStyle,
  HorizontalAlign,
  HideColumnCommand,
  HideRowCommand,
  HistoryCommand,
  IndexedSheetCommand,
  JsonValue,
  LocaleDefinition,
  LocaleMessages,
  MergeCommand,
  PaintFormatCommand,
  PasteEvent,
  PasteExternalCommand,
  PasteInternalCommand,
  PasteMode,
  RedoCommand,
  RemoveValidationCommand,
  RenameSheetCommand,
  ResizeColumnCommand,
  ResizeRowCommand,
  RowData,
  RowsData,
  Selection,
  SetBorderCommand,
  SetCellMetadataCommand,
  SetCellTextCommand,
  SetFilterCommand,
  SetFreezeCommand,
  SetStyleCommand,
  SetValidationCommand,
  SheetColumnOptions,
  SheetData,
  SheetId,
  SheetOptions,
  SheetRowOptions,
  SheetTabItem,
  SheetTabsRenderProps,
  SortCommand,
  TegoSheetError,
  TegoSheetErrorCode,
  ToolbarAction,
  ToolbarRenderProps,
  TransactionChangeAggregate,
  TransactionSheetChange,
  UndoCommand,
  ValidationData,
  ValidationIssue,
  ValidationOperator,
  ValidationResult,
  ValidationRule,
  ValidationType,
  VerticalAlign,
  WorkbookChange,
  WorkbookChangeKind,
  WorkbookCommand,
} from './core';
export { TegoSheetException } from './core';
export {
  createSpreadsheetDocument,
  migrateLegacyWorkbook,
  parseSpreadsheetDocument,
  serializeSpreadsheetDocument,
} from './document';
export { createDocumentController } from './document-controller';
export type {
  DocumentChange,
  DocumentChangedRange,
  DocumentCommand,
  DocumentCommandEnvelope,
  DocumentCommittedTransaction,
  DocumentController,
  DocumentControllerEvent,
  DocumentControllerOptions,
  DocumentControllerSnapshot,
  DocumentExecuteOptions,
  DocumentPatchOperation,
  DocumentSheetChange,
  DocumentTransactionDiagnostic,
  DocumentTransactionEnvelope,
  DocumentTransactionOptions,
  DocumentTransactionPermissionContext,
  DocumentTransactionPermissionGate,
  DocumentTransactionPreview,
  DocumentTransactionResult,
} from './document-controller';
export type {
  BindingId,
  Cell,
  CellInput,
  CreateDocumentOptions,
  Diagnostic,
  DiagnosticDomain,
  DiagnosticLocation,
  DiagnosticStage,
  DocumentCellAddress,
  DocumentCellRange,
  DocumentDiagnostic,
  DocumentDiagnosticCode,
  DocumentId,
  DocumentLimits,
  DocumentParseOptions,
  DocumentParseResult,
  DocumentSheetId,
  ExtensionStore,
  LegacyMigrationDiagnosticCode,
  LegacyMigrationIdFactory,
  LegacyMigrationOptions,
  MigrationDiagnostic,
  MigrationResult,
  ObjectId,
  PrintMargins,
  PrintProfile,
  RegistryEntry,
  ResourceId,
  ResourceMetadata,
  ResourceStore,
  Sheet,
  SheetColumn,
  SheetFilter,
  SheetFilterItem,
  SheetRange,
  SheetRow,
  SparseCell,
  SpreadsheetDocument,
  SpreadsheetTemplate,
  StyleId,
  StyleRegistry,
  TemplateId,
  ValidationId,
  ValidationRegistry,
  Workbook,
  WorkbookSettings,
} from './document';
/** A zero-based Workbook 2.0 cell coordinate. */
export type { CellPoint as DocumentCellPoint } from './document';
export { TegoSheet } from './react/tego-sheet';
export type {
  SheetTabsRenderer,
  TegoSheetHandle,
  TegoSheetProps,
  ToolbarRenderer,
} from './react/tego-sheet.types';
